# Generated by Django 5.2 on 2026-08-01 11:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SubDealers', '0005_delete_dacentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DACEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], help_text='Credit or Debit', max_length=2)),
                ('transaction_quantity', models.DecimalField(decimal_places=2, help_text='DAC Quantity', max_digits=14)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subdealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dac_entries', to='SubDealers.subdealer')),
            ],
            options={
                'db_table': 'DACEntry',
                'ordering': ['entry_date', 'created_at'],
            },
        ),
    ]
