# Generated by Django 5.2 on 2026-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDAC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dacentry',
            name='transaction_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='dacentry',
            name='transaction_type',
            field=models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2),
        ),
    ]
