# Generated by Django 5.2 on 2026-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'ordering': ['product_name']},
        ),
        migrations.AddField(
            model_name='productinventory',
            name='dac_applicable',
            field=models.BooleanField(default=False, help_text='Deduct DAC while selling this product.'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='productCode',
            field=models.CharField(blank=True, editable=False, help_text='Unique code for the product, auto-generated from the product name.', max_length=20, null=True, unique=True),
        ),
    ]
