# Generated by Django 5.2 on 2026-08-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productinventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='submission_required',
            field=models.BooleanField(default=False, help_text='Requires empty cylinders to be submitted.'),
        ),
    ]
