# Generated by Django 5.2 on 2026-08-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productinventory_submission_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Buy price per unit for this batch', max_digits=10)),
                ('quantity_added', models.PositiveIntegerField(help_text='Original batch size when stock was added')),
                ('quantity_remaining', models.PositiveIntegerField(help_text='Units still unsold from this batch')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.productinventory')),
            ],
            options={
                'db_table': 'stock_batch',
                'ordering': ['added_at'],
            },
        ),
    ]
