# Generated by Django 5.2 on 2026-08-17 14:23

from django.db import migrations


def seed_initial_batches(apps, schema_editor):
    """
    Create an initial StockBatch for every product that has stock > 0,
    using the current buy_price as the batch price.
    """
    ProductInventory = apps.get_model("inventory", "ProductInventory")
    StockBatch = apps.get_model("inventory", "StockBatch")

    batches_to_create = []
    for product in ProductInventory.objects.filter(product_quantity__gt=0):
        batches_to_create.append(
            StockBatch(
                product=product,
                buy_price=product.buy_price,
                quantity_added=product.product_quantity,
                quantity_remaining=product.product_quantity,
                notes="Initial batch (migrated from existing stock)",
            )
        )

    if batches_to_create:
        StockBatch.objects.bulk_create(batches_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_add_stock_batch"),
    ]

    operations = [
        migrations.RunPython(seed_initial_batches, migrations.RunPython.noop),
    ]
