# Generated by Django 5.2 on 2025-11-02 15:14

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='ac_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mixed', 'Mixed'), ('AC', 'AC')], default='Cash', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending Verification')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailyinvoice',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='dailyinvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='dailyinvoice',
            name='invoice_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailyinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='dailyinvoice',
            name='other_expense',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='dailyinvoice',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='dailyinvoicelineitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailyinvoicelineitem',
            name='due_cyl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyinvoicelineitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
