# Generated by Django 5.2 on 2026-05-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0002_dailyinvoicelineitem_ac_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DACEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subdealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dac_entries', to='SubDealers.subdealer')),
            ],
            options={
                'db_table': 'DACEntry',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
