# Generated by Django 5.2 on 2026-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0003_dacentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdealer',
            name='dac_percentage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='DAC percentage to apply for this subdealer', max_digits=5),
        ),
    ]
