# Generated by Django 5.2 on 2026-08-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0004_subdealer_dac_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DACEntry',
        ),
    ]
