# Generated by Django 5.2 on 2026-08-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0005_delete_dacentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
