# Generated by Django 5.2 on 2026-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0007_remove_dailyinvoicelineitem_due_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyinvoice',
            name='due_amount',
        ),
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
