# Generated by Django 5.2 on 2026-08-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0008_remove_dailyinvoice_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinvoicelineitem',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending Verification'), ('PARTIAL', 'Partial Payment')], default='PENDING', max_length=10),
        ),
    ]
