# Generated by Django 5.2 on 2026-08-01 18:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0009_alter_dailyinvoicelineitem_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='verified_ac_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual AC amount received after verification', max_digits=14),
        ),
        migrations.AlterField(
            model_name='dailyinvoicelineitem',
            name='ac_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original AC amount billed', max_digits=14),
        ),
        migrations.AlterField(
            model_name='dailyinvoicelineitem',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash collected during invoice creation', max_digits=14),
        ),
    ]
