# Generated by Django 5.2 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0010_dailyinvoicelineitem_verified_ac_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdealer',
            name='address',
            field=models.TextField(blank=True, help_text='Address of the subdealer', null=True),
        ),
    ]
