# Generated by Django 5.2 on 2026-08-07
from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def set_existing_buying_prices(apps, schema_editor):
    LineItem = apps.get_model("SubDealers", "DailyInvoiceLineItem")
    for item in LineItem.objects.select_related("product").iterator():
        if item.product_id:
            item.buying_price = item.product.buy_price * item.quantity
            item.save(update_fields=["buying_price"])


class Migration(migrations.Migration):

    dependencies = [
        ("SubDealers", "0011_alter_subdealer_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyinvoicelineitem",
            name="buying_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total buying cost for this invoice line",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="dailyinvoicelineitem",
            name="is_other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyinvoicelineitem",
            name="remarks",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dailyinvoicelineitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.productinventory",
            ),
        ),
        migrations.RunPython(set_existing_buying_prices, migrations.RunPython.noop),
    ]
