# Generated by Django 5.2 on 2026-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0012_add_other_invoice_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinvoicelineitem',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was verified', null=True),
        ),
    ]
